"""empty message

Revision ID: 608e72f70a39
Revises: eefaa44df807
Create Date: 2018-05-05 09:11:42.452586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '608e72f70a39'
down_revision = 'eefaa44df807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meals', sa.Column('price', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meals', 'price')
    # ### end Alembic commands ###
